name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Menghilangkan peringatan Node.js

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.121.0'
          extended: true

      - name: Fix Theme Compatibility
        run: |
          # Perbaikan otomatis kodingan tema yang jadul
          find themes/tranquilpeak/layouts -type f -exec sed -i 's/.Site.Author/.Site.Params.author/g' {} +
          # Pastikan folder public bersih
          rm -rf public

      - name: Build with Hugo
        run: |
          hugo --minify --baseURL "https://dittalyona28.github.io/ditta_story/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
